name: Delete Yesterday's Folder

on:
  schedule:
    - cron: '1 1 * * *'
  workflow_dispatch:

jobs:
  delete-folder:
    runs-on: ubuntu-latest
    # 关键：设置写入权限
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 允许获取完整历史，支持推送

      - name: Get yesterday's date
        id: date
        run: |
          yesterday=$(date -d "yesterday" +%Y-%m-%d)
          echo "YESTERDAY=$yesterday" >> $GITHUB_ENV
          
      - name: Delete folder
        id: delete
        run: |
          folder_path="$GITHUB_WORKSPACE/${{ env.YESTERDAY }}"
          changed=false
          if [ -d "$folder_path" ]; then
            rm -rf "$folder_path"
            changed=true
          fi
          echo "CHANGED=$changed" >> $GITHUB_ENV
          
      - name: Commit changes
        if: ${{ env.CHANGED == 'true' }}
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "删除昨日文件夹: ${{ env.YESTERDAY }}" || true
          # 使用 GITHUB_TOKEN 或 PERSONAL_ACCESS_TOKEN
          git push --force --quiet https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
